version: '3.8'

services:
  backend:
    container_name: backend-1
    build:
      context: ./backend
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
    volumes:
      - db-volume:/app/storage

  frontend:
    container_name: frontend-1
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8090:8090'
    environment:
      - NODE_ENV=production

volumes:
  db-volume: