version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app:cached
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - '80:80'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    stdin_open: true
    tty: true
